image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  ARTIFACT_REGISTRY: europe-west10-docker.pkg.dev/aisheai/docker-images

before_script:
  - echo "$GCP_ARTIFACT_SERVICE_KEY" > gcloud-service-key.json
  - docker login -u _json_key --password-stdin $ARTIFACT_REGISTRY < gcloud-service-key.json
build:
  script:
    - docker build -t $ARTIFACT_REGISTRY/core:$CI_COMMIT_SHA .
    - docker push $ARTIFACT_REGISTRY/core:$CI_COMMIT_SHA
    - docker tag $ARTIFACT_REGISTRY/core:$CI_COMMIT_SHA $ARTIFACT_REGISTRY/core:latest  # Tagging as latest
    - docker push $ARTIFACT_REGISTRY/core:latest  # Pushing latest tag
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      # changes:
      #   - Dockerfile
