LOADING_INDICATOR = "Loading...."
LOADING_BLOCK = [
    {
        "type": "section",
        "text": {"type": "mrkdwn", "text": LOADING_INDICATOR},
        # "accessory": {
        #     "type": "image",
        #     "image_url": "https://media.tenor.com/UnFx-k_lSckAAAAM/amalie-steiness.gif",
        #     "alt_text": "loading spinner",
        # },
    }
]
CUSTOM_SLACK_COMMANDS = ["/intragpt-health-check"]

# Tuple of top 50+ most used programming language file extensions, including all Elixir extensions
ALLOWED_FILE_EXTENSIONS = (
    ".java",
    ".py",
    ".c",
    ".cpp",
    ".js",
    ".html",
    ".css",
    ".php",
    ".cs",
    # ".rb",
    ".go",
    ".swift",
    ".ts",
    # ".r",
    ".sh",
    # ".pl",
    # ".m",
    ".sql",
    # ".kt",
    # ".rs",
    # ".groovy",
    ".lua",
    ".vb",
    # ".f",
    # ".s",
    # ".asm",
    # ".dart",
    # ".hs",
    # ".pas",
    # ".elm",
    # ".clj",
    # ".erl",
    # ".ada",
    # ".cob",
    # ".lisp",
    ".scm",
    # ".rkt",
    # ".d",
    # ".jl",
    ".ex",
    ".exs",
    ".eex",
    ".leex",
    ".heex",
    # ".f90",
    # ".cr",
    # ".nim",
    # ".v",
    # ".h",
    # ".hpp",
    # ".hxx",
    ".ipynb",
    # ".md",
)
